### ISSUE TITLE
Setup server that DIBS can access to store data

### ISSUE THREAD

**Issue by Karpo22** [shadowedice/DIBS#4]
This will allow greater functionality for DIBS, and open up the ability to do things like create user-specific reminders, create TL;DR bots, and other enhancements that utilize meta-data.

**Comment by shadowedice** [comment]
It would help to store off information for the FFXIV class. Could also look into pulling all of the MTG information to a database and reading from that instead of querying the website each time.

**Comment by karpowich22** [comment]
SQLite DB seems to be up and running decently.  Gonna vote to close this out.
