### ISSUE TITLE
Fix Stocks.py and remove extra code

### ISSUE THREAD

**Issue by shadowedice** [shadowedice/DIBS#5]
Fix Stocks.py to be able to retrieve stock information. Currently it says no ticker name exists. Also remove card_image function that was added by mistake.

**Comment by Karpo22** [comment]
this is gonna be a clusterfuck and I'm going to have to reorganize the entire stock, because Yahoo decided to get all fancy and guard against scraping.

**Comment by shadowedice** [comment]
I removed the extra code from Stocks.py.

**Comment by shadowedice** [comment]
I fixed it. Probably will break again shortly.
